import { Play, Noto_Sans } from 'next/font/google'
import './globals.css'

import Provider from './providers'
import { cls } from '@/utils'
import { Footer, Header } from '@/components/layout'

const noto_Sans = Noto_Sans({ weight: '400', subsets: ['latin'] })

export const metadata = {
  title: 'AI Demo',
  description: 'Generated by ALTAVA',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body
        className={cls(
          noto_Sans.className,
          'bg-gradient-to-tr',
          'from-grayscale-800 via-[#e8e2f0] to-[#fff]'
        )}>
        <Provider>
          <Header />
          <main className='px-4 md:px-0 overflow-hidden'>{children}</main>
          <Footer />
        </Provider>
      </body>
    </html>
  )
}
